spring:
  datasource:
    url: jdbc:mysql://47.101.148.216:3306/spider?characterEncoding=UTF-8
    username: spider
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 80